# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Harsh Days
email: jackkav at gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Development notes, currently interested in docker, meteor, nodejs.
  Upcoming challenges include load balancing, load testing and mongo
  indexing. Will try to publish my findings here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jackkav.github.io" # the base hostname & protocol for your site
twitter_username: jackkav
github_username:  jackkav

# Build settings
markdown: kramdown
